### PR TITLE
Update WebExtHot.runtime.js

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Review by crimx — APPROVED** [review]

**Comment by Jack-Works** [comment]
If `script-src: unsafe-eval` is not set in dev mode, HMR will fail because eval error

**Comment by crimx** [comment]
Thanks for the PR! LGTM. Should I publish now?

**Comment by Jack-Works** [comment]
No hurry, thank you

**Comment by crimx** [comment]
I meant is it good to go? Do you have more PRs? I can wait if you want to.

**Comment by Jack-Works** [comment]
No more changes currently.. It's working well in our environment

**Pull request merged**
